// Code generated by hand. regBuf's layout on amd64:
//
//	type regBuf struct {
//		ints   [9]uintptr         // offset   0 ..  71
//		ptrs   [9]unsafe.Pointer  // offset  72 .. 143
//		floats [15]float64        // offset 144 .. 263
//	}
//
// func redial(fun unsafe.Pointer, regs *regBuf)
//
// Replays the call captured in regs: loads the integer and float argument
// registers, calls fun — a bare ABIInternal code pointer, an itab.Fun entry —
// and stores the result registers back into regs. The method must pass
// nothing on the stack, which fitsFastPath guarantees.
//
// The $208 frame exists to house the callee's register-argument home slots:
// if the callee's morestack trampoline fires, it spills its argument
// registers there. Those homes are the callee's incoming argument area, so
// their pointers are adjusted on stack moves by the callee's own argument
// map — the same arrangement as the runtime's reflectcall wrappers.

//go:build amd64

#include "textflag.h"

// Integer argument registers on amd64: AX BX CX DI SI R8 R9 R10 R11.
// DX and R12 are scratch here: neither is an argument register.

TEXT ·redial(SB), NOSPLIT, $208-16
	// The frame holds no pointers of redial's own; the assembler rewrites
	// no_pointers_stackmap(SB) into an empty locals map.
	FUNCDATA $1, no_pointers_stackmap(SB)

	MOVQ	regs+8(FP), R12
	MOVQ	(0*8)(R12), AX
	MOVQ	(1*8)(R12), BX
	MOVQ	(2*8)(R12), CX
	MOVQ	(3*8)(R12), DI
	MOVQ	(4*8)(R12), SI
	MOVQ	(5*8)(R12), R8
	MOVQ	(6*8)(R12), R9
	MOVQ	(7*8)(R12), R10
	MOVQ	(8*8)(R12), R11

	MOVSD	(144+0*8)(R12), X0
	MOVSD	(144+1*8)(R12), X1
	MOVSD	(144+2*8)(R12), X2
	MOVSD	(144+3*8)(R12), X3
	MOVSD	(144+4*8)(R12), X4
	MOVSD	(144+5*8)(R12), X5
	MOVSD	(144+6*8)(R12), X6
	MOVSD	(144+7*8)(R12), X7
	MOVSD	(144+8*8)(R12), X8
	MOVSD	(144+9*8)(R12), X9
	MOVSD	(144+10*8)(R12), X10
	MOVSD	(144+11*8)(R12), X11
	MOVSD	(144+12*8)(R12), X12
	MOVSD	(144+13*8)(R12), X13
	MOVSD	(144+14*8)(R12), X14

	MOVQ	fun+0(FP), DX
	PCDATA	$1, $0
	CALL	DX

	MOVQ	regs+8(FP), R12
	MOVQ	AX, (0*8)(R12)
	MOVQ	BX, (1*8)(R12)
	MOVQ	CX, (2*8)(R12)
	MOVQ	DI, (3*8)(R12)
	MOVQ	SI, (4*8)(R12)
	MOVQ	R8, (5*8)(R12)
	MOVQ	R9, (6*8)(R12)
	MOVQ	R10, (7*8)(R12)
	MOVQ	R11, (8*8)(R12)

	MOVSD	X0, (144+0*8)(R12)
	MOVSD	X1, (144+1*8)(R12)
	MOVSD	X2, (144+2*8)(R12)
	MOVSD	X3, (144+3*8)(R12)
	MOVSD	X4, (144+4*8)(R12)
	MOVSD	X5, (144+5*8)(R12)
	MOVSD	X6, (144+6*8)(R12)
	MOVSD	X7, (144+7*8)(R12)
	MOVSD	X8, (144+8*8)(R12)
	MOVSD	X9, (144+9*8)(R12)
	MOVSD	X10, (144+10*8)(R12)
	MOVSD	X11, (144+11*8)(R12)
	MOVSD	X12, (144+12*8)(R12)
	MOVSD	X13, (144+13*8)(R12)
	MOVSD	X14, (144+14*8)(R12)

	RET
