// Code generated by hand. regBuf's layout:
//
//	type regBuf struct {
//		ints   [16]uintptr        // offset   0 .. 127
//		ptrs   [16]unsafe.Pointer // offset 128 .. 255
//		floats [16]float64        // offset 256 .. 383
//	}
//
// func redial(fun unsafe.Pointer, regs *regBuf)
//
// Replays the call captured in regs: loads the integer and float argument
// registers, calls fun — a bare ABIInternal code pointer, an itab.Fun entry —
// and stores the result registers back into regs. The method must pass
// nothing on the stack, which fitsFastPath guarantees.
//
// The $272 frame exists to house the callee's register-argument home slots:
// if the callee's morestack trampoline fires, it spills its argument
// registers there. Those homes are the callee's incoming argument area, so
// their pointers are adjusted on stack moves by the callee's own argument
// map — the same arrangement as the runtime's reflectcall wrappers.

//go:build arm64

#include "textflag.h"

TEXT ·redial(SB), NOSPLIT, $272-16
	// The frame holds no pointers of redial's own; the assembler rewrites
	// no_pointers_stackmap(SB) into an empty locals map.
	FUNCDATA $1, no_pointers_stackmap(SB)

	MOVD	regs+8(FP), R17
	MOVD	(0*8)(R17), R0
	MOVD	(1*8)(R17), R1
	MOVD	(2*8)(R17), R2
	MOVD	(3*8)(R17), R3
	MOVD	(4*8)(R17), R4
	MOVD	(5*8)(R17), R5
	MOVD	(6*8)(R17), R6
	MOVD	(7*8)(R17), R7
	MOVD	(8*8)(R17), R8
	MOVD	(9*8)(R17), R9
	MOVD	(10*8)(R17), R10
	MOVD	(11*8)(R17), R11
	MOVD	(12*8)(R17), R12
	MOVD	(13*8)(R17), R13
	MOVD	(14*8)(R17), R14
	MOVD	(15*8)(R17), R15

	FMOVD	(256+0*8)(R17), F0
	FMOVD	(256+1*8)(R17), F1
	FMOVD	(256+2*8)(R17), F2
	FMOVD	(256+3*8)(R17), F3
	FMOVD	(256+4*8)(R17), F4
	FMOVD	(256+5*8)(R17), F5
	FMOVD	(256+6*8)(R17), F6
	FMOVD	(256+7*8)(R17), F7
	FMOVD	(256+8*8)(R17), F8
	FMOVD	(256+9*8)(R17), F9
	FMOVD	(256+10*8)(R17), F10
	FMOVD	(256+11*8)(R17), F11
	FMOVD	(256+12*8)(R17), F12
	FMOVD	(256+13*8)(R17), F13
	FMOVD	(256+14*8)(R17), F14
	FMOVD	(256+15*8)(R17), F15

	MOVD	fun+0(FP), R17
	PCDATA	$1, $0
	CALL	(R17)

	MOVD	regs+8(FP), R17
	MOVD	R0, (0*8)(R17)
	MOVD	R1, (1*8)(R17)
	MOVD	R2, (2*8)(R17)
	MOVD	R3, (3*8)(R17)
	MOVD	R4, (4*8)(R17)
	MOVD	R5, (5*8)(R17)
	MOVD	R6, (6*8)(R17)
	MOVD	R7, (7*8)(R17)
	MOVD	R8, (8*8)(R17)
	MOVD	R9, (9*8)(R17)
	MOVD	R10, (10*8)(R17)
	MOVD	R11, (11*8)(R17)
	MOVD	R12, (12*8)(R17)
	MOVD	R13, (13*8)(R17)
	MOVD	R14, (14*8)(R17)
	MOVD	R15, (15*8)(R17)

	FMOVD	F0, (256+0*8)(R17)
	FMOVD	F1, (256+1*8)(R17)
	FMOVD	F2, (256+2*8)(R17)
	FMOVD	F3, (256+3*8)(R17)
	FMOVD	F4, (256+4*8)(R17)
	FMOVD	F5, (256+5*8)(R17)
	FMOVD	F6, (256+6*8)(R17)
	FMOVD	F7, (256+7*8)(R17)
	FMOVD	F8, (256+8*8)(R17)
	FMOVD	F9, (256+9*8)(R17)
	FMOVD	F10, (256+10*8)(R17)
	FMOVD	F11, (256+11*8)(R17)
	FMOVD	F12, (256+12*8)(R17)
	FMOVD	F13, (256+13*8)(R17)
	FMOVD	F14, (256+14*8)(R17)
	FMOVD	F15, (256+15*8)(R17)

	RET
