// Code generated by weave.StubSource; DO NOT EDIT.

//go:build arm64

package weave

import (
	"unsafe"
)

// weaveStub_m0_a18_15555_r16_5555 is the precise trampoline for:
//
//	weave.StackPtrs.Both func(string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string) (string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
//
// method 0, 18 argument words (pointers 0x15555), 16 result words (pointers 0x5555).
//
// go:nosplit keeps the morestack trampoline from spilling the register
// arguments into home slots the interface call site never reserved, and
// go:norace keeps the race prologue from doing the same.
//
//go:nosplit
//go:norace
func weaveStub_m0_a18_15555_r16_5555(
	a0 uintptr,
	a1 uintptr,
	a2 uintptr,
	a3 uintptr,
	a4 uintptr,
	a5 uintptr,
	a6 uintptr,
	a7 uintptr,
	a8 uintptr,
	a9 uintptr,
	a10 uintptr,
	a11 uintptr,
	a12 uintptr,
	a13 uintptr,
	a14 uintptr,
	a15 uintptr,
	f0 float64,
	f1 float64,
	f2 float64,
	f3 float64,
	f4 float64,
	f5 float64,
	f6 float64,
	f7 float64,
	f8 float64,
	f9 float64,
	f10 float64,
	f11 float64,
	f12 float64,
	f13 float64,
	f14 float64,
	f15 float64,
	// 18 words of stack-assigned arguments:
	w0 unsafe.Pointer,
	w1 uintptr,
	w2 unsafe.Pointer,
	w3 uintptr,
	w4 unsafe.Pointer,
	w5 uintptr,
	w6 unsafe.Pointer,
	w7 uintptr,
	w8 unsafe.Pointer,
	w9 uintptr,
	w10 unsafe.Pointer,
	w11 uintptr,
	w12 unsafe.Pointer,
	w13 uintptr,
	w14 unsafe.Pointer,
	w15 uintptr,
	w16 unsafe.Pointer,
	w17 uintptr,
	// 16 words the stack-assigned results will occupy:
	w18 unsafe.Pointer,
	w19 uintptr,
	w20 unsafe.Pointer,
	w21 uintptr,
	w22 unsafe.Pointer,
	w23 uintptr,
	w24 unsafe.Pointer,
	w25 uintptr,
	w26 unsafe.Pointer,
	w27 uintptr,
	w28 unsafe.Pointer,
	w29 uintptr,
	w30 unsafe.Pointer,
	w31 uintptr,
	w32 unsafe.Pointer,
	w33 uintptr,
) (
	r0 unsafe.Pointer,
	r1 unsafe.Pointer,
	r2 unsafe.Pointer,
	r3 unsafe.Pointer,
	r4 unsafe.Pointer,
	r5 unsafe.Pointer,
	r6 unsafe.Pointer,
	r7 unsafe.Pointer,
	r8 unsafe.Pointer,
	r9 unsafe.Pointer,
	r10 unsafe.Pointer,
	r11 unsafe.Pointer,
	r12 unsafe.Pointer,
	r13 unsafe.Pointer,
	r14 unsafe.Pointer,
	r15 unsafe.Pointer,
	g0 float64,
	g1 float64,
	g2 float64,
	g3 float64,
	g4 float64,
	g5 float64,
	g6 float64,
	g7 float64,
	g8 float64,
	g9 float64,
	g10 float64,
	g11 float64,
	g12 float64,
	g13 float64,
	g14 float64,
	g15 float64,
) {
	base := unsafe.Pointer(&w0)

	// The result words still hold whatever the caller's frame held
	// before this call, and the pointer map above now says some of them
	// are pointers. Clear those before the first safe point — a nosplit
	// function has none until its first call — so the collector never
	// sees a stale word through the new map.
	*(*uintptr)(unsafe.Add(base, 144)) = 0
	*(*uintptr)(unsafe.Add(base, 160)) = 0
	*(*uintptr)(unsafe.Add(base, 176)) = 0
	*(*uintptr)(unsafe.Add(base, 192)) = 0
	*(*uintptr)(unsafe.Add(base, 208)) = 0
	*(*uintptr)(unsafe.Add(base, 224)) = 0
	*(*uintptr)(unsafe.Add(base, 240)) = 0
	*(*uintptr)(unsafe.Add(base, 256)) = 0

	return Dispatch(0, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, base)
}

// weaveStub_m1_a18_15555_r0_0 is the precise trampoline for:
//
//	weave.StackPtrs.ManyPtrs func(string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string) int
//
// method 1, 18 argument words (pointers 0x15555), 0 result words (pointers 0x0).
//
// go:nosplit keeps the morestack trampoline from spilling the register
// arguments into home slots the interface call site never reserved, and
// go:norace keeps the race prologue from doing the same.
//
//go:nosplit
//go:norace
func weaveStub_m1_a18_15555_r0_0(
	a0 uintptr,
	a1 uintptr,
	a2 uintptr,
	a3 uintptr,
	a4 uintptr,
	a5 uintptr,
	a6 uintptr,
	a7 uintptr,
	a8 uintptr,
	a9 uintptr,
	a10 uintptr,
	a11 uintptr,
	a12 uintptr,
	a13 uintptr,
	a14 uintptr,
	a15 uintptr,
	f0 float64,
	f1 float64,
	f2 float64,
	f3 float64,
	f4 float64,
	f5 float64,
	f6 float64,
	f7 float64,
	f8 float64,
	f9 float64,
	f10 float64,
	f11 float64,
	f12 float64,
	f13 float64,
	f14 float64,
	f15 float64,
	// 18 words of stack-assigned arguments:
	w0 unsafe.Pointer,
	w1 uintptr,
	w2 unsafe.Pointer,
	w3 uintptr,
	w4 unsafe.Pointer,
	w5 uintptr,
	w6 unsafe.Pointer,
	w7 uintptr,
	w8 unsafe.Pointer,
	w9 uintptr,
	w10 unsafe.Pointer,
	w11 uintptr,
	w12 unsafe.Pointer,
	w13 uintptr,
	w14 unsafe.Pointer,
	w15 uintptr,
	w16 unsafe.Pointer,
	w17 uintptr,
) (
	r0 unsafe.Pointer,
	r1 unsafe.Pointer,
	r2 unsafe.Pointer,
	r3 unsafe.Pointer,
	r4 unsafe.Pointer,
	r5 unsafe.Pointer,
	r6 unsafe.Pointer,
	r7 unsafe.Pointer,
	r8 unsafe.Pointer,
	r9 unsafe.Pointer,
	r10 unsafe.Pointer,
	r11 unsafe.Pointer,
	r12 unsafe.Pointer,
	r13 unsafe.Pointer,
	r14 unsafe.Pointer,
	r15 unsafe.Pointer,
	g0 float64,
	g1 float64,
	g2 float64,
	g3 float64,
	g4 float64,
	g5 float64,
	g6 float64,
	g7 float64,
	g8 float64,
	g9 float64,
	g10 float64,
	g11 float64,
	g12 float64,
	g13 float64,
	g14 float64,
	g15 float64,
) {
	base := unsafe.Pointer(&w0)

	return Dispatch(1, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, base)
}

// weaveStub_m2_a0_0_r16_5555 is the precise trampoline for:
//
//	weave.StackPtrs.ManyStrs func(int) (string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
//
// method 2, 0 argument words (pointers 0x0), 16 result words (pointers 0x5555).
//
// go:nosplit keeps the morestack trampoline from spilling the register
// arguments into home slots the interface call site never reserved, and
// go:norace keeps the race prologue from doing the same.
//
//go:nosplit
//go:norace
func weaveStub_m2_a0_0_r16_5555(
	a0 uintptr,
	a1 uintptr,
	a2 uintptr,
	a3 uintptr,
	a4 uintptr,
	a5 uintptr,
	a6 uintptr,
	a7 uintptr,
	a8 uintptr,
	a9 uintptr,
	a10 uintptr,
	a11 uintptr,
	a12 uintptr,
	a13 uintptr,
	a14 uintptr,
	a15 uintptr,
	f0 float64,
	f1 float64,
	f2 float64,
	f3 float64,
	f4 float64,
	f5 float64,
	f6 float64,
	f7 float64,
	f8 float64,
	f9 float64,
	f10 float64,
	f11 float64,
	f12 float64,
	f13 float64,
	f14 float64,
	f15 float64,
	// 16 words the stack-assigned results will occupy:
	w0 unsafe.Pointer,
	w1 uintptr,
	w2 unsafe.Pointer,
	w3 uintptr,
	w4 unsafe.Pointer,
	w5 uintptr,
	w6 unsafe.Pointer,
	w7 uintptr,
	w8 unsafe.Pointer,
	w9 uintptr,
	w10 unsafe.Pointer,
	w11 uintptr,
	w12 unsafe.Pointer,
	w13 uintptr,
	w14 unsafe.Pointer,
	w15 uintptr,
) (
	r0 unsafe.Pointer,
	r1 unsafe.Pointer,
	r2 unsafe.Pointer,
	r3 unsafe.Pointer,
	r4 unsafe.Pointer,
	r5 unsafe.Pointer,
	r6 unsafe.Pointer,
	r7 unsafe.Pointer,
	r8 unsafe.Pointer,
	r9 unsafe.Pointer,
	r10 unsafe.Pointer,
	r11 unsafe.Pointer,
	r12 unsafe.Pointer,
	r13 unsafe.Pointer,
	r14 unsafe.Pointer,
	r15 unsafe.Pointer,
	g0 float64,
	g1 float64,
	g2 float64,
	g3 float64,
	g4 float64,
	g5 float64,
	g6 float64,
	g7 float64,
	g8 float64,
	g9 float64,
	g10 float64,
	g11 float64,
	g12 float64,
	g13 float64,
	g14 float64,
	g15 float64,
) {
	base := unsafe.Pointer(&w0)

	// The result words still hold whatever the caller's frame held
	// before this call, and the pointer map above now says some of them
	// are pointers. Clear those before the first safe point — a nosplit
	// function has none until its first call — so the collector never
	// sees a stale word through the new map.
	*(*uintptr)(unsafe.Add(base, 0)) = 0
	*(*uintptr)(unsafe.Add(base, 16)) = 0
	*(*uintptr)(unsafe.Add(base, 32)) = 0
	*(*uintptr)(unsafe.Add(base, 48)) = 0
	*(*uintptr)(unsafe.Add(base, 64)) = 0
	*(*uintptr)(unsafe.Add(base, 80)) = 0
	*(*uintptr)(unsafe.Add(base, 96)) = 0
	*(*uintptr)(unsafe.Add(base, 112)) = 0

	return Dispatch(2, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, base)
}

func init() {
	RegisterStub(StubSpec{Index: 0, ArgWords: 18, RetWords: 16, ArgPtrs: 0x15555, RetPtrs: 0x5555, Func: weaveStub_m0_a18_15555_r16_5555})
	RegisterStub(StubSpec{Index: 1, ArgWords: 18, RetWords: 0, ArgPtrs: 0x15555, RetPtrs: 0x0, Func: weaveStub_m1_a18_15555_r0_0})
	RegisterStub(StubSpec{Index: 2, ArgWords: 0, RetWords: 16, ArgPtrs: 0x0, RetPtrs: 0x5555, Func: weaveStub_m2_a0_0_r16_5555})
}
