// Code generated by gen/main.go; DO NOT EDIT.

//go:build amd64

package weave

import "unsafe"

const slotCount = 128

//go:nosplit
//go:norace
func stub0(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(0, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub1(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(1, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub2(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(2, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub3(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(3, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub4(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(4, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub5(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(5, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub6(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(6, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub7(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(7, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub8(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(8, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub9(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(9, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub10(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(10, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub11(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(11, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub12(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(12, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub13(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(13, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub14(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(14, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub15(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(15, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub16(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(16, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub17(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(17, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub18(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(18, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub19(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(19, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub20(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(20, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub21(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(21, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub22(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(22, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub23(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(23, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub24(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(24, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub25(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(25, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub26(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(26, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub27(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(27, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub28(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(28, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub29(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(29, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub30(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(30, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub31(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(31, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub32(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(32, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub33(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(33, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub34(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(34, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub35(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(35, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub36(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(36, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub37(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(37, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub38(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(38, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub39(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(39, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub40(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(40, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub41(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(41, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub42(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(42, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub43(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(43, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub44(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(44, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub45(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(45, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub46(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(46, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub47(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(47, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub48(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(48, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub49(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(49, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub50(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(50, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub51(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(51, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub52(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(52, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub53(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(53, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub54(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(54, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub55(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(55, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub56(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(56, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub57(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(57, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub58(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(58, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub59(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(59, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub60(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(60, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub61(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(61, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub62(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(62, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub63(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(63, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub64(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(64, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub65(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(65, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub66(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(66, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub67(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(67, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub68(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(68, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub69(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(69, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub70(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(70, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub71(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(71, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub72(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(72, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub73(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(73, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub74(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(74, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub75(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(75, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub76(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(76, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub77(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(77, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub78(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(78, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub79(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(79, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub80(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(80, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub81(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(81, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub82(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(82, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub83(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(83, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub84(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(84, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub85(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(85, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub86(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(86, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub87(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(87, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub88(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(88, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub89(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(89, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub90(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(90, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub91(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(91, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub92(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(92, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub93(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(93, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub94(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(94, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub95(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(95, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub96(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(96, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub97(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(97, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub98(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(98, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub99(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(99, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub100(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(100, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub101(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(101, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub102(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(102, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub103(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(103, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub104(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(104, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub105(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(105, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub106(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(106, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub107(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(107, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub108(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(108, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub109(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(109, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub110(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(110, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub111(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(111, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub112(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(112, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub113(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(113, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub114(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(114, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub115(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(115, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub116(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(116, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub117(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(117, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub118(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(118, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub119(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(119, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub120(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(120, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub121(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(121, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub122(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(122, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub123(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(123, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub124(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(124, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub125(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(125, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub126(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(126, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

//go:nosplit
//go:norace
func stub127(a0, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14 float64, s0 [stackWindow]byte) (r0, r1, r2, r3, r4, r5, r6, r7, r8 unsafe.Pointer, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14 float64) {
	return Dispatch(127, a0, a1, a2, a3, a4, a5, a6, a7, a8, f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, unsafe.Pointer(&s0))
}

var stubs = [...]fastFunc{
	stub0,
	stub1,
	stub2,
	stub3,
	stub4,
	stub5,
	stub6,
	stub7,
	stub8,
	stub9,
	stub10,
	stub11,
	stub12,
	stub13,
	stub14,
	stub15,
	stub16,
	stub17,
	stub18,
	stub19,
	stub20,
	stub21,
	stub22,
	stub23,
	stub24,
	stub25,
	stub26,
	stub27,
	stub28,
	stub29,
	stub30,
	stub31,
	stub32,
	stub33,
	stub34,
	stub35,
	stub36,
	stub37,
	stub38,
	stub39,
	stub40,
	stub41,
	stub42,
	stub43,
	stub44,
	stub45,
	stub46,
	stub47,
	stub48,
	stub49,
	stub50,
	stub51,
	stub52,
	stub53,
	stub54,
	stub55,
	stub56,
	stub57,
	stub58,
	stub59,
	stub60,
	stub61,
	stub62,
	stub63,
	stub64,
	stub65,
	stub66,
	stub67,
	stub68,
	stub69,
	stub70,
	stub71,
	stub72,
	stub73,
	stub74,
	stub75,
	stub76,
	stub77,
	stub78,
	stub79,
	stub80,
	stub81,
	stub82,
	stub83,
	stub84,
	stub85,
	stub86,
	stub87,
	stub88,
	stub89,
	stub90,
	stub91,
	stub92,
	stub93,
	stub94,
	stub95,
	stub96,
	stub97,
	stub98,
	stub99,
	stub100,
	stub101,
	stub102,
	stub103,
	stub104,
	stub105,
	stub106,
	stub107,
	stub108,
	stub109,
	stub110,
	stub111,
	stub112,
	stub113,
	stub114,
	stub115,
	stub116,
	stub117,
	stub118,
	stub119,
	stub120,
	stub121,
	stub122,
	stub123,
	stub124,
	stub125,
	stub126,
	stub127,
}
